openapi: '3.0.3'
info:
  title: Image Processing Service Api
  version: '1.0'
servers:
  - url: https://localhost:8080/api
    description: Local development server

tags:
  - name: Auth
    description: Controller methods related to authentication
  - name: Images
    description: Controller methods related to Images

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          example: test@gmail.com
        password:
          type: string
      required:
        - email
        - password

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          
    RegisterRequest:
      type: object
      properties:
        name:
          type: string
          example: test
        email:
          type: string
          example: test@gmail.com
        password:
          type: string
      required:
        - name
        - email
        - password
    
    ImageDetailsResponse:
      type: object
      properties:
        imageId:
          type: string
          description: "Unique identifier for the image"
          example: "img_7890abc"
        imageUrl:
          type: string
          description: "The public URL where the image is hosted"
          example: "https://storage.googleapis.com/bucket/image.jpg"
        userId:
          type: string
          description: "The ID of the user who owns the image"
          example: "user_12345"
        isDeleted:
          type: boolean
          description: "Flag indicating if the image has been soft-deleted"
          example: false
        createdAt:
          type: string
          format: date-time
          description: "The timestamp when the record was created (ISO-8601)"
          example: "2023-11-01T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: "The timestamp when the record was last updated (ISO-8601)"
          example: "2023-11-01T12:30:00Z"
      required:
        - imageId
        - imageUrl
        - userId
        - isDeleted
        - createdAt
        - updatedAt
    
    ImageResponsePage:
      allOf:
        - $ref: '#/components/schemas/PageableObject'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/ImageDetailsResponse'
    
    PageableObject:
      type: object
      properties:
        page:
          type: integer
          example: 0
        size:
          type: integer
          example: 10
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        last:
          type: boolean
    
    DeleteImagesRequest:
      type: object
      properties:
        imageIds:
          type: array
          description: "A list of unique image identifiers to be deleted"
          items:
            type: string
            example: "img_7890abc"
      required:
        - imageId

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message


paths:
  /api/auth/test:
    get:
      tags:
        - Auth
      summary: Health check Api
      operationId: testApp
      responses:
        '200':
          description: Ok
          content: 
            application/json:
              schema:
                type: string
  
  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login api route
      operationId: loginUser
      requestBody: 
        required: true
        content: 
          application/json:
            schema: 
              $ref: "#/components/schemas/LoginRequest"
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/auth/register:
    post: 
      tags:
        - Auth
      summary: Register api route
      operationId: registerUser
      requestBody: 
        required: true
        content: 
          application/json:
            schema: 
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        '200':
          description: Successfully registered
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/image:
    get:
      tags:
        - Images
      summary: Return pageable response of images
      operationId: getAllImages
      parameters:
          - name: page
            in: query
            description: Page number
            required: true
            schema:
              type: integer
          - name: pageSize
            in: query
            description: Page 
            required: true
            schema:
              type: integer

      responses:
        '200':
          description: Pageable response of images
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageResponsePage"
        '500':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete: 
      tags:
        - Images
      summary: Deletes images
      operationId: deleteImagesByIds
      requestBody: 
        required: true
        content: 
          application/json:
            schema: 
              $ref: "#/components/schemas/DeleteImagesRequest"
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      

  /api/image/upload:
    post:
      tags:
        - Images
      summary: Uploads image to server
      operationId: uploadImage
      requestBody: 
        required: true
        content: 
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                height:
                  type: integer
                width:
                  type: integer
              required:
                - file
                - height
                - width
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/image/{id}:
    get: 
      tags:
        - Images
      summary: Gets image detais by id
      operationId: getImageById
      parameters:
        - name: id
          in: path
          description: Image id of image
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageDetailsResponse"
        '404':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

