spring.application.name=pixiflow

spring.datasource.url=jdbc:postgresql://localhost:5432/pixiflowdb
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=ykZSko2zQBkcMZXADDh5Vgrpf/bj2huPdr4yOxsPy5Y=
jwt.expiration-ms=3600000
