spring.application.name=pixiflow

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION}

aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}
aws.s3.region=${AWS_S3_REGION}
aws.s3.bucketName=${AWS_S3_BUCKET_NAME}

clientUrl=${CLIENT_URL}
